import Head from 'next/head'
import Image from 'next/image'
// import estilos from '../styles/Boostrao.module.css'
import { useRouter } from 'next/router';

export default function Home() {
  const router = useRouter();
  let hola = router.locale == 'en-US' ? "Hello" : 'es' ? "Hola" : ";"
  let Administracion = router.locale == 'en-US' ? "Management" : 'es' ? "Administración" : ";"
  return (
    <div>
      <Head>
        <title>FullStore {Administracion}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <script src="https://kit.fontawesome.com/812c8ee19a.js" crossOrigin="anonymous"></script> */}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossOrigin="anonymous"></link>
      </Head>

      <nav className="navbar navbar-dark bg-dark">
        <div className="container">
          <a className="navbar-brand" href="#">
            <Image src="/logo.svg" alt="Vercel Logo" width={160} height={50} />
          </a>
          <div className="d-flex">
            <div className="dropdown">
              <button className="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                <a href="/es">Español</a> 
              </button>
              <button  className="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                <a href="/en-us">Inglés</a> 
              </button>
              <button className="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
              <a href="/fr-FR">Francés</a>
              </button>
              <ul className="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <li><a className="dropdown-item" href="#">Cerrar Sesión</a></li>
              </ul>
            </div>
          </div>
        </div>
      </nav>

      <main>
        <div className="card text-center m-4">
          <div className="card-header bg-dark">
            {Administracion}
          </div>
          <div className="card-body">
            <div className="text-end">
              <button className="btn btn-danger mb-3"><i className="fa-solid fa-user-plus"></i> Agregar Producto</button>
            </div>

            <table className="table">
              <thead className="table-dark">
                <tr>
                  <td>Nombres</td>
                  <td>Apellido Paterno</td>
                  <td>Apellido Materno</td>
                  <td>Celular</td>
                  <td>Correo</td>
                  <td>Editar</td>
                  <td>Eliminar</td>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Raúl</td>
                  <td>Díaz</td>
                  <td>Cabrera</td>
                  <td>929481296</td>
                  <td>72806558@certus.edu.pe</td>
                  <td><button className="btn btn-primary"><i className="fa-solid fa-pen-to-square"></i> Editar</button></td>
                  <td><button className="btn btn-danger"><i className="fa-solid fa-trash-can"></i> Eliminar</button></td>
                </tr>
              </tbody>
            </table>
          </div>
          <div className="card-footer text-muted">
            FullStore S.A.C.
          </div>
        </div>
      </main>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossOrigin="anonymous"></script>
    </div>
  )
}
